### ISSUE TITLE
App doesn't update location 

### ISSUE THREAD

**Issue by Reedyn** [destil/WearSquare#8]
I'm constantly getting the same choices from the same location when using the app, regardless of where I am located. Been having this issue the past 2 weeks

**Comment by destil** [comment]
Do you have location services enabled in your Android phone? If you launch Google Maps, do you have good location there?

**Comment by Reedyn** [comment]
Yes, it works for all other apps, including apps that use location on Android Wear, such as Maps Mini.

**Comment by destil** [comment]
Can you test it a little? When do you get the old location? If you launch Google Maps and then launch Wearsquare, is it better?

**Comment by Reedyn** [comment]
I can do some testing tomorrow, I'm currently at the location where it always gives me choices from :)

**Comment by Reedyn** [comment]
I've done some testing today. First I did the following test *(when being located at work)*

 1. Try to update location through WearSquare *(Got the old choices from my location at home)*
 2. Open Google Maps on phone and Maps Mini on Android Wear and got the exact location.
 3. Try to update location through WearSquare *(Got the same old choices from my location at home)*

Then I tried the following:

 1. Try to update location through WearSquare *(Got the old choices from my location at home)*
 2. Update location through Swarm by Foursquare app on my phone.
 3. Try to update location through WearSquare *(Now it shows the same choices as I got from the Android app)*

I did the same test again when I came home and now it refuses to update from my location at work.

**Comment by destil** [comment]
Thanks for testing. Let's investigate more. It works fine for me.

I'm using a passive location provider - it should update location when some other app requests location. This way it's very battery-efficient. 

My app is not tight location-wise with official Swarm app, so that's just random. 

Maybe I need more information about your environment?
- please attach screenshot of your Settings -> Location screen
- do you have WiFi enabled all the time, even when you are not connected to any WiFi? That helps determining location a lot.

**Comment by destil** [comment]
Pinging @radeksimko - You had the same problem right?

**Comment by Reedyn** [comment]
Here's a screenshot of my location settings. Did some more testing (same as before), nothing I do seems to reproduce the problem; Sometimes it's there, sometimes it's not.

![](http://gustavlindqvist.se/content/images/2015/01/Screenshot_2015-01-09-15-33-02.png)

**Comment by radeksimko** [comment]
Yeah, I had exactly the same issue. I accidentally managed to check in via WearSquare in Prague while actually being in London (location old ~2 days).

<img src="https://cloud.githubusercontent.com/assets/287584/5693648/1c52f6a2-991e-11e4-99c4-d562f6517f9e.png" width="350">

I have WiFi enabled most of the time, rarely turn it off, but afaik when it happens, I have the WiFi on (so best location should be available).

As @Reedyn mentioned, the issue appears quite randomly.

**Comment by destil** [comment]
Thanks for detailed feedback. I think I have fixed it - when location is older than two minutes, I specifically ask for a new location. That might take some time (average 4 seconds during my testing) but you shouldn't be stuck with old location. 

Can you please test it first before I roll it out to everyone? I published it to beta: https://plus.google.com/communities/101759563856154570864

**Comment by radeksimko** [comment]
> Can you please test it first before I roll it out to everyone?

Well, I assume we can test it now, but as mentioned earlier, the bug appears de facto randomly, so even if it will work, it doesn't guarantee it's fixed.

**Comment by Reedyn** [comment]
As @radeksimko said since it appears randomly it's hard to say it is fixed. 

However that said. It's worked the past 2 times I've tried it now :)

**Comment by Reedyn** [comment]
It's been working flawlessly today for me

**Comment by destil** [comment]
I will wait one more day, if you don't report any issue, I will push it to production.

**Comment by destil** [comment]
No complaints, I have pushed it to production.
